version: '3'
services:

  mysql:
    image: mysql:8.0
    networks:
      - danal_network
    command: --init-file=/docker-entrypoint-initdb.d/01_create_table.sql
    volumes:
      - ./db/conf.d:/etc/mysql/conf.d
      - ./db/data:/var/lib/mysql
      - ./db/initdb.d:/docker-entrypoint-initdb.d
    ports:
      - '3306:3306'
    environment:
      - TZ=Asia/Seoul
      - MYSQL_ROOT_PASSWORD=rootpw
      - MYSQL_DATABASE=danal_batch
      - MYSQL_USER=mysqluser
      - MYSQL_PASSWORD=mysqlpw
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-umysqluser", "-pmysqlpw" ]
      interval: 5s
      timeout: 10s
      retries: 5

  batch-service:
    image: danal-batch-service:1.0.0
    networks:
      - danal_network
    ports:
      - '8081:8080'
    depends_on:
      mysql:
        condition: service_healthy
    restart: on-failure

networks:
  danal_network:
    driver: bridge